package com.funk.vocables;

public enum PronounKind {
	FRENCH_PERSONAL_CONNECTED, FRENCH_PERSONAL_UNCONNECTED, FRENCH_POSSESIVE, FRENCH_OBJECT_DIRECT, FRENCH_OBJECT_INDIRECT,
	FRENCH_DEMONSTRATIVE_COMPANION, FRENCH_DEMONSTRATIVE;
}
