package com.funk.vocables;

public enum Tempus {
	FRENCH_PRESENT, FRENCH_IMPARFAIT, FRENCH_PASSE_COMPOSE, FRENCH_FUTUR_SIMPLE, FRENCH_FUTUR_COMPOSE, FRENCH_FUTUR_ANTERIEUR,
	FRENCH_PASSE_SIMPLE;
}
